---
# tasks file for roles/dbserver
- name: Install Python MySQL packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3-pymysql
    - python3-mysql.connector

- name: install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present
  notify: start mysql service  

- name: start mysql service
  ansible.builtin.service:
    name: mysql
    state: started
  become: true

- name: check if .my.cnf file exist    #if yes so root user is created before
  stat:
    path: ~/.my.cnf
  register: mycnf

- name: Set MySQL root password and authentication
  shell: |
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
  when: not mycnf.stat.exists


- name: deploy mysql .my.cnf for root user
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    mode: '0600'
  notify:
    - Restart mysql service
