---
# tasks file for roles/webserver
- name: Install Apache and PHP
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apache2
    - php
    - libapache2-mod-php

- name: Deploy Apache config template
  ansible.builtin.template:
    src: apache2.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache

- name: Enable Apache site configuration
  ansible.builtin.command:
    cmd: a2ensite 000-default.conf
  notify: Restart Apache

- name: deploy phpinfo.php for testing PHP
  ansible.builtin.copy:
    src: phpinfo.php
    dest: "{{ apache_document_root }}/phpinfo.php"


- name: Start and enable Apache
  ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
